"""message

Revision ID: ecd2cc9d5694
Revises: d1b8dd43efe0
Create Date: 2024-02-14 09:09:59.881263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd2cc9d5694'
down_revision = 'd1b8dd43efe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
